name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
      
  deploy:
    runs-on: ubuntu-latest
    env:
      LEIN_PASSWORD: ${{ secrets.LEIN_PASSWORD }}
      LEIN_USERNAME: ${{ secrets.LEIN_USERNAME }}
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to clojars
      run: lein deploy
