name: Clojure CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LEIN_PASSWORD: ${{ secrets.LEIN_PASSWORD }}
      LEIN_USERNAME: ${{ secrets.LEIN_USERNAME }}
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Increment version
      run: lein bump-version
    - name: Deploy to clojars
      run: lein deploy
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[POST-RELEASE] Increment version" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
